### ISSUE TITLE
TAP 3: Unspecified targets

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/taps#10]
I'm not sure if a TAP can be amended (or if an amendment is needed in the following case), but while reviewing the accepted version of TAP 3  I noticed that targets are never specified in the examples.

I kept reading comments like:
```
// We specify the name, keyids, and threshold of a single role allowed to sign the following targets.
```

Here is one example from the TAP:

```
{
  "signed": {
    "delegations": {
      "roles": [
        // This is the first delegation to a single role.
        {
          // We specify the name, keyids, and threshold of a single role allowed
          // to sign the following targets.
          // Each role uses a filename based on its rolename.
          "name": ROLENAME-1,
          "keyids": [KEYID-1],
          "threshold": THRESHOLD-1,
          ...
        },
        // This is the second delegation to a single role.
        // Note that this delegation is separate from the first one.
        // The first delegation may override this delegation.
        {
          "name": ROLENAME-2,
          "keyids": [KEYID-2],
          "threshold": THRESHOLD-2,
          ...
        }
        // Note that, unfortunately, there is no way to require multiple
        // roles to sign targets in a single delegation.
      ],
      ...
    },
    ...
}
```

**Comment by awwad** [comment]
True: that's probably confusing to readers. "the following targets": this
is never actually specified (no paths)

You'd expect the actual paths to appear there somewhere.

        {
          "name": ROLENAME-2,
          "keyids": [KEYID-2],
          "threshold": THRESHOLD-2,
          "paths": ["/django/*.dbm"],    // or what have you

          ...

        }


Talking about delegations without having that piece of the delegation is
probably confusing.

(On a related note, consider actual target examples, too ("targets":
{"/django/183.dbm": {"hashes": {...}, length: x} }}. It's probably not
worth it, given the format the TAP is written in: you'd need to write the
delegated target role files out. It should be a considered decision,
though.)

**Comment by JustinCappos** [comment]
Sure, it's fine to make small amendments like this.  Go ahead and push /
change.

**Comment by vladimir-v-diaz** [comment]
Before making these edits, I'd like to confirm that the list of targets being delegated is placed in the expected field.

Previously, delegated targets were placed in the "paths" field of a delegated role like so:

```
{ "name": ROLENAME-2,
  "keyids": [KEYID-2],
  "threshold": THRESHOLD-2,
  "paths": ["/django/*.dbm"],
}
```

In multi-role delegations, delegated targets can either be placed in a single "paths" entry shared by multiple roles, or in separate "paths" for each delegated role.  I suspect it's the former, but I need to verify.

It's not covered in the TAP, but which format is correct?

(1)
```
{
  // Both roles must sign the same hashes and length of the following targets.
  "paths": [/django/*.dbm, /django/LICENSE.txt],
  "names": {
    ROLENAME-1: {
      "keyids": [KEYID-1],
      "threshold": THRESHOLD-1
    },
    ROLENAME-2: {
      "keyids": [KEYID-2],
      "threshold": THRESHOLD-2
    }
  }
}
```

(2)
```
{
  // Both roles must sign the same hashes and length of the following targets.
  "names": {
    ROLENAME-1: {
      "keyids": [KEYID-1],
      "threshold": THRESHOLD-1,
      "paths": [/django/*.dbm, /django/LICENSE.txt]
    },
    ROLENAME-2: {
      "keyids": [KEYID-2],
      "threshold": THRESHOLD-2,
      "paths": [/django/*.dbm, /django/LICENSE.txt]
    }
  }
}
```

**Comment by trishankkarthik** [comment]
@vladimir-v-diaz (1)

**Comment by JustinCappos** [comment]
I agree

**Comment by awwad** [comment]
It's 1, yes. That (paths) used to be in there. Paths are the things being delegated, so their presence there helps show what is actually happening.

**Comment by trishankkarthik** [comment]
Can we close this now, @vladimir-v-diaz and @awwad ?

**Comment by vladimir-v-diaz** [comment]
Sure!
