### ISSUE TITLE
Removing assumed TAP numbers in PR

### ISSUE THREAD

**Issue by erickt** [theupdateframework/taps#109]
I've noticed there have been some collisions for future TAP numbers: like for TAP 11 with #74 and #106, and TAP 12, with #103 and #107. According to [TAP 1](https://github.com/theupdateframework/taps/blob/master/tap1.md#submitting-a-tap), numbers are supposed to be assigned when a proposal has been accepted. If this is the case, could these proposals be renamed to avoid confusion when discussing proposals?

**Comment by JustinCappos** [comment]
Good point.  Perhaps we should have names like candidate-_few word description_.MD for the files before a TAP number is assigned.  @mnm678 , what do you think?

**Comment by mnm678** [comment]
I agree, the overlapping numbers are confusing. I can rename the proposed TAPs that I submitted.

**Comment by JustinCappos** [comment]
Okay, please send a PR that fixes this across the repo.

**Comment by mnm678** [comment]
I removed the TAP number in #106 and #107. I don't think I have permission to change the filename in #74.

**Comment by mnm678** [comment]
#74 was closed, so all proposed TAPs no longer have numbers assigned.
