### ISSUE TITLE
Inaccuracies in TAP 4

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/taps#110]
The following sentence is inaccurate:

`A "terminating" flag that instructs the updater whether to continue searching subsequent mappings after failing to download requested target files from the repositories specified in the first mapping.`

First, it's not about failing to "download," but failing to find the target files. Second, it's not the "first mapping," but the current mapping IF it is matches the requested target file.

**Comment by JustinCappos** [comment]
good catch.  Would you like to propose an edit and I'll review and merge?

**Comment by trishankatdatadog** [comment]
Don't have the time right now, but will try to send one soon...

**Comment by joshuagl** [comment]
This was addressed in #117 and can now be closed.
