### ISSUE TITLE
Assign # to keyid flexibility TAP?

### ISSUE THREAD

**Issue by brainwane** [theupdateframework/taps#114]
Now that #112 has been merged, should `candidate-keyid-tap.md` get a number and go into the list/index in the README?

**Comment by jhdalek55** [comment]
I would make it easier ti find, thus better facilitating discussion.

**Comment by mnm678** [comment]
Yes, I will submit a pr to add a TAP number in accordance with [TAP 1](https://github.com/theupdateframework/taps/blob/master/tap1.md).
