### ISSUE TITLE
Discussion of TAP 13: User Selection of the Top-Level Target Files Through Mapping Metadata

### ISSUE THREAD

**Issue by JustinCappos** [theupdateframework/taps#119]
This is the place to debate this TAP.  Please @ others we should add.

Fire away!

**Comment by lukpueh** [comment]
Thanks for opening the debate, @JustinCappos. Since we already have PR #118, should we not just keep everything?

**Comment by JustinCappos** [comment]
Good point.  I was trying to follow the instructions and was a bit duplicative.  :)  Closing...
