### ISSUE TITLE
Allowing TAPs that are licensed with MIT or Apache 2.0?

### ISSUE THREAD

**Issue by erickt** [theupdateframework/taps#126]
Good morning. The [TAP-2](https://github.com/theupdateframework/taps/blob/master/tap2.md) template states that TAPs must be placed in public domain, or licensed with [Open Publication License](https://opencontent.org/openpub/). Would you also consider allowing for TAPs that are licensed with MIT or Apache 2.0?

**Comment by erickt** [comment]
Note that [Rust](https://github.com/rust-lang/rfcs#contributions) dual licenses their RFCs with MIT and Apache 2.0, and [Swift](https://github.com/apple/swift-evolution) and [Kubernetes](https://github.com/kubernetes/enhancements) license their extensions with Apache 2.0.

**Comment by trishankatdatadog** [comment]
A few questions:
1. What are the pros and cons of dual-licensing?
2. Would this apply retrospectively? Presumably not, and that is probably fine.

**Comment by erickt** [comment]
1. Unfortunately I am not qualified to answer on the pros and cons of dual licensing. Does CNCF has resources to help answer that kind of question?
2. For my purposes, I wouldn't needed the change to be retroactive. I would just prefer to use one or the other to post new TAPs.

**Comment by mnm678** [comment]
cc @JustinCappos

**Comment by erickt** [comment]
@trishankatdatadog I don't currently have approval to submit changes under Open Publication License, but I do with MIT or Apache 2.0. It would be convenient for me to avoid having to seek approval from work. Also pre-approved are creative commons licenses like [CC-By](https://creativecommons.org/licenses/by/4.0/) if that's more appropriate.

**Comment by trishankatdatadog** [comment]
Got it, thanks for the explanation, Eric!

**Comment by JustinCappos** [comment]
I'm not savvy enough to know how to answer this.  I think we should ask
folks at the CNCF for advice.  I'm looping in Chris A who hopefully can
help to direct this.

**Comment by erickt** [comment]
@JustinCappos: Good morning! Has there been any word from Chris A?

**Comment by JustinCappos** [comment]
There hasn't.  Adding Amye and pinging again...

**Comment by caniszczyk** [comment]
The CNCF IP policy requires code to be Apache v2.0 and docs under CC-BY:

https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy

If dual licensing this as Apache v2.0 + CC-BY works for you that's fine (even though it isn't code per se).

**Comment by joshuagl** [comment]
Should we be updating the TAP process (TAP 1 & 2) to request TAPs are either explicitly labeled as placed in the public domain (see this TAP as an example) or licensed under Creative Commons Attribution 4.0 International License?

Thus removing the use of the Open Publication License for new TAPs?
