### ISSUE TITLE
Support for downgrading/revoking a version?

### ISSUE THREAD

**Issue by jvilimek** [theupdateframework/taps#180]
Dears,
Is this the right place (since the discussion is empty)? If not, please navigate me to the proper place/process.

When dealing with **production issues** sometimes these are caused by introducing a new version of a package deployed from TUF. Currently, I am not aware of any ways we can revert (downgrade) deployment to the last known working version of the package.
Is this something I shall introduce as TAP?

Another improvement (or earlier mitigation of the production issues) would be A/B testing or rolling deployment (10%... 20%... 50% of clients...) or rings (beta/pre-release/early-adopters/slow-ring...).

WDYT?

____________________________________
**ANSWER**: we need to implement this ourselves in our client(s).

**Comment by lukpueh** [comment]
Great question, @jvilimek! TUF actually does not have any semantics for package versions. As far as TUF is concerned, the version of a package is just part of its name and downgrading from "my-package-v2" to "my-package-v1", is just a change of package (i.e. target).

What TUF does care about is the version of the corresponding metadata, so that the client always has a fresh view of the repository, even if that fresh view includes an older package than the previous view.

**Comment by lukpueh** [comment]
> Another improvement (or earlier mitigation of the production issues) would be A/B testing or rolling deployment (10%... 20%... 50% of clients...) or rings (beta/pre-release/early-adopters/slow-ring...).

This sounds very reasonable. Though, I don't think any of this needs a TAP, which is the formal process for specification changes. Instead I would discuss this as part of deployment considerations / best practices. We have an open issue here: https://github.com/theupdateframework/specification/issues/91

**Comment by jvilimek** [comment]
> Great question, @jvilimek! TUF actually does not have any semantics for package versions. As far as TUF is concerned, the version of a package is just part of its name and downgrading from "my-package-v2" to "my-package-v1", is just a change of package (i.e. target).
> 
> What TUF does care about is the version of the corresponding metadata, so that the client always has a fresh view of the repository, even if that fresh view includes an older package than the previous view.

Thanks for the quick reply! Let me elaborate on this a bit:

What is now the principle the TUF client knows there is a version it needs to install? AFAIK it installs the latest version, right?

This is the current structure of TUF json:
```json
{
    "signatures": [...],
    "signed": {
        "_type": "targets",
        "expires": "2024-01-12T14:59:21Z",
        "spec_version": "1.0",
        "targets": {
            "some-namespace/1.0.1019/some-file.zip": {
                "hashes": {
                    "sha512": "4060b38ab...074d30f83cc82"
                },
                "length": 35673351
            },
            "some-namespace/1.0.1019/other-file.yaml": {
                "hashes": {
                    "sha512": "fe0403da52...198ec2be92dbb33"
                },
                "length": 807
            },
            ...
      }
}
```

How about changing this a little bit: 

```json
{
    "signatures": [],
    "signed": {
        "_type": "targets",
        "expires": "2024-01-12T14:59:21Z",
        "spec_version": "2.0",
        "targets": {
            "some-namespace": {
                "current_version": "1.0.1019", // <<<-- this we can change even downwards
                "all_versions": [
                    {
                        "version": "1.0.1019",
                        "status": "active", // valid | revoked | not-supported | ...
                        "some-file.zip": {
                            "length": 35673351,
                            "sha512-hash": "4060b38abc...01f83cc82"
                        },
                        "other-file.yaml": {
                            "length": 807,
                            "sha512-hash": "4060b38abc...30f83cc82"
                        }
                    }
                ]
            }
        }
    }
}
```

(for backward compatibility, you can keep `targets.json` and introduce a new `targets2.json`?)

**Comment by jvilimek** [comment]
> > Another improvement (or earlier mitigation of the production issues) would be A/B testing or rolling deployment (10%... 20%... 50% of clients...) or rings (beta/pre-release/early-adopters/slow-ring...).
> 
> This sounds very reasonable. Though, I don't think any of this needs a TAP, which is the formal process for specification changes. Instead I would discuss this as part of deployment considerations / best practices. We have an open issue here: [theupdateframework/specification#91](https://github.com/theupdateframework/specification/issues/91)

have you send a correct link? This one navigates to an issue "Secondary literature with detailed rationale and recommendations"?

**Comment by JustinCappos** [comment]
I'll also chime in that Uptane (which is a variant of TUF) has a
centralized party that controls what versions of software are pushed out to
different clients.  So looking there may also answer many of your
questions...

**Comment by jvilimek** [comment]
> Hey @jvilimek, thanks for reaching out. Firstly, would you please elaborate on your exact issue? 

Thanks @trishankatdatadog for the reply. Sure, I will elaborate. By production issue I mean the following:
- we are using TUF for deploying plugins among our clients. This plugin sends some data to our services in the cloud.
- let's say we have deployed version 1.0 to DEV, STG, and to PROD environment (=among all our clients)
- we start deploying (and testing) version 1.1 to DEV, then STG ... no issue is found. 
- then we deploy this version to PROD and suddenly our services in the cloud start crashing and/or are overloaded.
- we want to revert the deployment and re-install version 1.0 among our clients (on all environments)

Sure.. you can argue that we should have found the issue in the DEV or STG environment. But no testing process is 100% successful and cases like this just happen.

**Comment by jvilimek** [comment]
> I'll also chime in that Uptane (which is a variant of TUF) has a centralized party that controls what versions of software are pushed out to different clients. So looking there may also answer many of your questions...

Thanks, we will check this for sure!

**Comment by jvilimek** [comment]
I do understand now. We need to implement this by ourselves in our client(s). Thanks for your patience with me and for the quick answers!
