### ISSUE TITLE
Meta: Proposal to leave an acceptance issue open per TAP so other projects can link back to it

### ISSUE THREAD

**Issue by heartsucker** [theupdateframework/taps#31]
For each unaccepted TAP, there should be an issue called "Acceptance of TAP X" so that other projects can easily link back to the discussion, and there is a unified place to see which projects are interested in which TAP. Additionally, this should link back to the original issues/PRs that generated the TAP in the first place.

**Comment by vladimir-v-diaz** [comment]
I think this is a good proposal.  I'll go ahead and open issues for TAPs 3-9.

**Comment by vladimir-v-diaz** [comment]
Okay, issues have been created for TAPs 3-9.

Let me know if I should include anything else in the issue summaries.  I'm not so sure about listing the projects that are interested in a certain feature introduced by a TAP.  Most of the TAPs were inspired by discussions with members of certain communities, while others were directly contributed by these individuals, which you can see from the TAP's author field.

**Comment by vladimir-v-diaz** [comment]
> and there is a unified place to see which projects are interested in which TAP.

Ahh, I understand now.  Links made from other repositories will indeed help us keep track of interest expressed by other repositories/projects.

**Comment by vladimir-v-diaz** [comment]
I am closing this now since the GitHub issues were created and there we no reported problems.
