### ISSUE TITLE
Discussion of TAP 3: Multi-role delegations

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/taps#32]
TAP 3 proposal is available at https://github.com/theupdateframework/taps/blob/master/tap3.md

Pull requests related to TAP 3:
https://github.com/theupdateframework/taps/pull/3
https://github.com/theupdateframework/taps/pull/7
https://github.com/theupdateframework/taps/pull/9
https://github.com/theupdateframework/taps/pull/11
https://github.com/theupdateframework/taps/pull/12

**Comment by vladimir-v-diaz** [comment]
@JustinCappos @trishankkarthik @awwad 

I came across a few issues with the format of delegations (as proposed in TAP 3) while working on its implementation.  My proposed changes to TAP 3 can be viewed here:
https://gist.github.com/vladimir-v-diaz/827d1513c75c48d70591ee47ed33f38e

Let me know if you agree with the changes and my justification for changing TAP 3.

**Here is a list of the proposed changes:**

(1) "keys" is moved outside of "delegations" and renamed "keys_for_delegations"

(2) Add "name" to "delegations", which is associated with a group/multi-role delegation

(3) Rename "names" to "roleinfo"

(4) "roleinfo" (previously "names") is a list so that delegations are ordered

(5) "threshold" for a multi-role delegation is renamed "min_roles_in_agreement" 


**Reasons for changes:**

(1) If "keys" is kept within "delegations", we'll have to use a dict.  Unfortunately, we lose the ability to order the delegations.  I think "keys_for_delegations" is a clearer name.

(2) In the implementation, I need some way of referring to a muti-role
delegation.  For example, let's say I delegate like so: targets.delegate([role1, role2, ...], ...).  How do I refer to this multi-role delegation?  And how do I revoke it?  And if it's a long list of multiple roles?
I'd like to instead do the following:
repository.targets("claimed").revoke("my_multi-role_delegation")

(3) "names" doesn't quite capture what it contains, and it clashes with "name"

(4) Made into a list so that the roles can be ordered.

(5) Renamed to "min_roles_in_agreement" so that is doesn't clash with
the "threshold" listed inside "roleinfo"

**Comment by JustinCappos** [comment]
So effectively, suggestion 1 just removes the 'delegations' dictionary and promotes / renames the 'roles' item that was within that dictionary.  I don't have a problem with this.  It just is a renaming change, as far as I see.

Similarly, 3 and 5 are also fine with me.  They just seem to improve clarity without impacting security / functionality.  

Changes 2 and 4 need to be clarified / discussed more, but I'm fine with the other changes.

**Comment by vladimir-v-diaz** [comment]
I'll cover suggestion (4) in this reply.

The "names" field (renamed to "roleinfo") is [currently a dictionary](https://github.com/theupdateframework/taps/blob/master/tap3.md), as you can see here:
```
{
          // These targets must be signed by both of these roles.
          "paths": ["/baz/*.pkg"],
          "terminating", true,
          "names": {
            // The release engineering role must sign using this key.
            "release-engineering": {
              "keyids": [
                "1a2b4110927d4cba257262f614896179ff85ca1f1353a41b5224ac474ca71cb4"
              ],
              "threshold": 1
            },
            // The quality assurance role must sign using at least 2/3 of these keys.
            "quality-assurance": {
              "keyids": [
                "93ec2c3dec7cc08922179320ccd8c346234bf7f21705268b93e990d5273a2a3b",
                "f2d5020d08aea06a0a9192eb6a4f549e17032ebefa1aa9ac167c1e3e727930d6",
                "fce9cf1cc86b0945d6a042f334026f31ed8e4ee1510218f198e8d3f191d15309"
              ],
              "threshold": 2
            }
          },
          ...
}
```

I propose we change "names"/"roleinfo" to a list, so that that roles are ordered and the client can choose the target specified by the first matching role(s), according to "min_roles_in_agreement.
Here's what the change looks like:
https://gist.github.com/vladimir-v-diaz/827d1513c75c48d70591ee47ed33f38e#file-multi-role_delegation-txt-L48-L60

**Comment by vladimir-v-diaz** [comment]
Here is my clarification of suggestion (2).

I suggest we add the "name" field to each multi-role delegation, as demonstrated on line 44 here:
https://gist.github.com/vladimir-v-diaz/827d1513c75c48d70591ee47ed33f38e#file-multi-role_delegation-txt-L42-L61

Without an identifier, how can the client easily refer to this multi-role delegation without having to use the full list of delegations in the "roleinfo" field:
```repository.targets.revoke([role1, role2, role3])```

Or some unreadable approach like:

```repository.targets.revoke('3')```, which refers to the 3rd multi-role delegation in the Targets' "delegations" entry.

**Comment by hannesm** [comment]
@vladimir-v-diaz I like your changes! :)  I'm not entirely sure about `name` (I need some mechanism like this as well for key rotation/TAP8): in your example, how is uniqueness of names guaranteed?  maybe a mechanism to fully qualify names is needed (using the delegation chain, starting from target, as prefix?) -- another solution may be to concatenate the public keys and hash over them.

**Comment by vladimir-v-diaz** [comment]
@hannesm 
Glad to hear that you find the proposal useful.

It's true, there is no guarantee that "name" is unique.  For example, it is possible for there to be duplicate "names" in the "delegations" field of role X.  However, since role X is performing the delegation, it is likely that it will choose unique names, no?  I guess we can recommend that the delegator use unique names in this case.

I thought about using hashes to avoid duplicates, but the hashes would be inconvenient to use.

For instance, ```repository.targets.revoke('123456778...')`  The goal is to make it easy to refer to a particular multi-role delegation.

**Comment by vladimir-v-diaz** [comment]
I am closing this issue tracker since TAP 3 has been accepted.  We'd like to keep corresponding issue trackers open only for the pending TAPs.

Note: While implementing TAP 3 a number of issues have been found with the accepted TAP.  I have suggested fixes for these issues here, and await final confirmation from @JustinCappos for my clarified suggestions (2) and (4) here:
https://github.com/theupdateframework/taps/issues/32#issuecomment-318088641

**Comment by JustinCappos** [comment]
I'm fine with both of these changes.
