### ISSUE TITLE
Discussion of TAP 5: Setting URLs for roles in the root metadata file

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/taps#34]
TAP 5 proposal is available at https://github.com/theupdateframework/taps/blob/master/tap5.md

Pull requests related to TAP 5:
https://github.com/theupdateframework/taps/pull/4
https://github.com/theupdateframework/taps/pull/5
https://github.com/theupdateframework/taps/pull/6
https://github.com/theupdateframework/taps/pull/15

**Comment by heartsucker** [comment]
Based off the two issues I just linked above, it should be noted that the `URLs` field should be altered to not be a URL but also a path. This would allow simple relative paths on the all servers/mirrors. That is, every mirror might have the same directory structure and be identical, and in one line it could be noted that the `root.json` is under `meta/root.json`.

**Comment by JustinCappos** [comment]
I'm confused by what you are asking for.  A URL can contain a path, right?
https://en.wikipedia.org/wiki/URL

**Comment by heartsucker** [comment]
Let's say I have repo `tuf.example.com` and it mirrors to `tuf.foo.com` and `tuf.bar.com`, but on all 3, I have the metadata served from `meta/*.json` and the targets are still from `/`. I want to be able to express that more simply. That is, all mirrors always have the metadata served from `/meta`. Doing it with the URLs notation would require each mirror to have separate roots that all point to `$self/meta` for the different pieces. This is more related to https://github.com/theupdateframework/tuf/issues/463 than this issue itself, but I guess I wanted to express a perceived shortcoming here.

**Comment by vladimir-v-diaz** [comment]
@heartsucker Can you give us an example of the notation you'd like for TAP 5 to support?

Are you saying that the following is unwieldy, for example?

```
"root": {
         // Fix the root role to keys controlled by the group of enterprise
         // users instead of PyPI administrators.
        "keyids": [...],
        // And update the root metadata file from a privately controlled server.
        "URLs": ["http://tuf.example.com/metadata/root.json",
            "tuf.foo.com/metadata/root.json, "tuf.bar.com/metadata/root.json"],
        ...
      },
```

**Comment by mnm678** [comment]
Closing discussion for rejected TAP.
