### ISSUE TITLE
Inconsistent wording for the trusted Root file in spec's detailed workflow and unneeded subsection

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/taps#47]
We should try to use a single, consistent word for the currently trusted Root file.

In particular,
[1.3 & 1.4](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L977-L985) refer to "current root metadata file"
[3.2](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L1035-L1036) refers to the same file as the "previous root metadata file"

[4.2](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L1076-L1078) and [4.4](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L1084-L1085) refer to the same file as the "latest root metadata file"

[Subsections 0 and 0.1](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L952-L957) might also contradict each other.

**Comment by awwad** [comment]
One option we discussed is to write at the end of 1.3 something like "Version N+1 is now the trusted root metadata file." and then use "trusted root file" in all cases.

Alternatively, we could update them all to "current root metadata file". This is somewhat less clear on careful reading, but perhaps clearer to someone skimming.

**Comment by vladimir-v-diaz** [comment]
I have moved this issue to the TUF repository.  The TAPs repo isn't the place for this issue.

**Comment by jhdalek55** [comment]
If I can weigh in here, I think "trusted root metadata file," probably works better than "current" as a "standardized" term for the document as a  whole.

**Comment by vladimir-v-diaz** [comment]
@awwad Feel free to repost your comment here: 
https://github.com/theupdateframework/tuf/issues/458

**Comment by trishankkarthik** [comment]
Although I don't have a preference, I don't think "trusted root metadata file" always works better than "current root metadata file."

Consider the following [context](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L979-L980): "a threshold of keys specified in the current root metadata file (version N+1)."

It's a little strange to say "trusted" here instead of "current", because we haven't trusted it yet, we're still checking it.

I'll leave this up to you all.

**Comment by awwad** [comment]
@trishankkarthik In 1.3 and 1.4, the root versions are numbered and the currently trusted file is actually N, so we can be even clearer. I'd probably put 1.3 and 1.4 this way: (Changes are bracketed [].)

    1.3. **Check signatures.** Version N+1 of the root metadata file MUST have
    been signed by: (1) a threshold of keys specified in the currently trusted root
    metadata file (version N), and (2) a threshold of keys specified in the
    [new] root metadata file [being validated] (version N+1).

    1.4. **Check for a rollback attack.** The version number of the [currently
    trusted] metadata file [(N)] must be less than or equal to the version number of [the
    new] root metadata file [(N+1)]. Effectively, this means checking that the version
    number signed in the [new] root metadata file is indeed N+1.

There's a bit of hand waving in 1.4 where we sort of imply that the new file doesn't have to have had version N+1 after all, even though we've been calling it N+1. If people think that's confusing, which I could imagine, it could be rewritten with versions identified as X and Y and given example values 6 and 7, say, in parentheticals. NBD, though.
