### ISSUE TITLE
TAP 4: misleading graphic

### ISSUE THREAD

**Issue by awwad** [theupdateframework/taps#90]
Regarding TAP 4, in section [Searching for Files on Multiple Repositories](https://github.com/theupdateframework/taps/blob/79313bf4c415f82c4a7ec8194fdac408bdef9ea5/tap4.md#searching-for-files-on-multiple-repositories):

The graphic explaining the foo-1.0.tgz situation is either confusing or wrong:
 It reads:	`"If a match for foo-1.0.tgz had not been found, the search would have terminated. Since the third mapping's pattern is set to *, it will always match with foo-1.0.tgz."`  But the 2nd delegation has terminating set to False in the graphic, so, no, the search would *not* have terminated, but would have continued to the 3rd delegation.

On a related, minor note: item 4 in this section should read `"If the metadata is not a match, or if fewer than the threshold of repositories signed metadata about the desired target.."`

**Comment by vladimir-v-diaz** [comment]
I agree that the caption is confusing.  Do you find the following revision clearer?

> If a match for foo-1.0.tgz is not found, the search terminates.  Since the third mapping’s pattern is set to `*`, it will always match with foo-1.0.tgz.  The catch-all pattern (`*`) guarantees that at least one repository is contacted for any request.

**Comment by awwad** [comment]
Ah. I think that part of the problem for me was that given the arrow down from step 2 and the "Contact repositories D and F" line directly above the line in question, with the same alignment, it looks like the line is talking about what happens in step 2. I gather it was intended to talk about the whole set of steps, after completion?

**Comment by vladimir-v-diaz** [comment]
Yes, the caption is for the whole set of steps.  In other words, the caption is for the entire figure.

**Comment by vladimir-v-diaz** [comment]
I’ll try adding a box around the entire figure and the caption outside the box.

**Comment by awwad** [comment]
K. It didn't look like that to me. Yes, such a box would work.

I don't think it's necessary to talk about whether or not, when all the options have been searched, the search terminated. (What else could it do but terminate?) Maybe `If none of the three mappings matched foo-1.0.tgz, no repository is contacted.`
