### ISSUE TITLE
TAP 4: potentially confusing explanation of delegations

### ISSUE THREAD

**Issue by awwad** [theupdateframework/taps#91]
(minor)

TAP 4's section [Mechanism that Assigns Targets to Repositories](https://github.com/theupdateframework/taps/blob/79313bf4c415f82c4a7ec8194fdac408bdef9ea5/tap4.md#mechanism-that-assigns-targets-to-repositories) provides a list of what is required for each mapping.

There are a few issues:
#### First:
Item A is worded such that it can be misread as referring to multiple mappings: `"A. An ordered list of one or more repositories. When the updater is instructed to download metadata or target files, it tries each repository in the order listed."` This can be cleared up a bit by adding "in the delegation" after "tries each repository".

Consider also adding `"until a threshold of repositories in agreement about the metadata has been reached"` to the "in the order listed" line.

Consider also having "Each mapping contains the following elements:" be on its own line to draw more attention to the list's label (which is currently just the end of a paragraph).

#### Second:
Item D should be worded better, I think. It currently reads `"D. A threshold that indicates the minimum number of repositories that are required to sign for the same length and hash of a requested target as specified by element (B)."` It sounds like the length and hash (or just hash) of a requested target is specified by element B..?

It should read something like `D. A threshold indicating the minimum number of the repositories (listed in B) that are required to sign for the same information for the requested target (length and hash) for that target information to be considered valid.`

If not, it at least needs a comma before "as specified by element (B)".

**Comment by vladimir-v-diaz** [comment]
> Item A is worded such that it can be misread as referring to multiple mappings: "A. An ordered list of one or more repositories. When the updater is instructed to download metadata or target files, it tries each repository in the order listed."

Immediately before Item A is "Each mapping contains the following elements:".  Do you think it's necessary to clarify that it's the repositories in a particular mapping, given that previous sentence?

You recommend:

> This can be cleared up a bit by adding "in the delegation" after "tries each repository".

Do you mean "in the mapping?"
