### ISSUE TITLE
TAP 4: example mentions unknown functionality

### ISSUE THREAD

**Issue by awwad** [theupdateframework/taps#92]
TAP 4: example mentions unknown functionality
In section [Example using the Reference Implementation's Map File](https://github.com/theupdateframework/taps/blob/79313bf4c415f82c4a7ec8194fdac408bdef9ea5/tap4.md#example-using-the-reference-implementations-map-file):

There is an unexplained bit about excluding URLs:
```
	      // Some paths need not have a URL.  Then those paths will not be updated.
	      ...
```

First: There's no detail for this no-URL no-update feature anywhere else in the TAP. (We've discussed it outside the TAP, but it's not in there.)
 
Second: This is a feature of repositories in the map file, not paths. Paths don't have a URL. Paths map to a repository, which might in turn not have a URL assigned. Further, if that delegation is encountered before others and is terminating, then the targets delegated by that delegation will not be updated. The priority between delegations and the settings in delegations determine this behavior.

**Comment by vladimir-v-diaz** [comment]
As discussed offline, this is likely a remnant of TAP 5.

The [new root metadata file format](https://github.com/theupdateframework/taps/blob/master/tap5.md#the-new-root-metadata-file-format) section of TAP 5 explains that the URL attribute can be empty:

> There are three cases regarding this attribute. If this list is specified, but empty, then this metadata file shall not be updated at all.

I don't think we wish to support something of the sort in TAP 4.
