### ISSUE TITLE
TAP 4: directories may help conceptualize target namespace delegation

### ISSUE THREAD

**Issue by awwad** [theupdateframework/taps#93]
(minor)

In [TAP 4](https://github.com/theupdateframework/taps/blob/79313bf4c415f82c4a7ec8194fdac408bdef9ea5/tap4.md), there seem to be no path delegation examples that use directories. Since that's actually how we usually do this, it seems like we should switch one. (It may also be easier to conceptualize or find useful than glob patterns, which can feel chaotic?)

**Comment by vladimir-v-diaz** [comment]
Just to be sure...  Are you requesting that we specify a path that does not contain a (*) wildcard?

For example, does this work for you?
```
// Map the target "/django/django-2.0.tgz" to both Django and PyPI.
      "paths":        ["/django/django-2.0.tgz"],
      "repositories": ["Django", "PyPI"],
```

**Comment by awwad** [comment]
Sure, yeah. It's... not a big deal. It's just a thought to consider. I was thinking something like "/django/*", but that works.
